# config/services.yaml

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # On récupère la clé définie dans le fichier .env
    app.weather_api_key: '%env(OPENWEATHER_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        
        # Le BIND permet de dire à Symfony : 
        # "Chaque fois que tu vois un argument nommé $weatherApiKey dans un constructeur, 
        # injecte la valeur du paramètre app.weather_api_key"
        bind:
            $weatherApiKey: '%app.weather_api_key%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration du service PlantService avec son token API
    App\Service\PlantService:
        arguments:
            $trefleApiToken: '%env(TREFLE_API_TOKEN)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
